INFO 2025-09-11 14:05:10,103 autoreload 22588 8786976960 Watching for file changes with StatReloader
ERROR 2025-09-11 14:05:41,370 log 22588 6246445056 Internal Server Error: /admin/authentication/customuser/1/change/
Traceback (most recent call last):
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/options.py", line 840, in get_form
    return modelform_factory(self.model, **defaults)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/forms/models.py", line 654, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/forms/models.py", line 312, in __new__
    fields = fields_for_model(
        opts.model,
    ...<11 lines>...
        form_declared_fields=new_class.declared_fields,
    )
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/forms/models.py", line 207, in fields_for_model
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: 'date_joined' cannot be specified for CustomUser model form as it is a non-editable field

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1987, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1840, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1878, in _changeform_view
    ModelForm = self.get_form(
        request, obj, change=not add, fields=flatten_fieldsets(fieldsets)
    )
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/auth/admin.py", line 98, in get_form
    return super().get_form(request, obj, **defaults)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/options.py", line 842, in get_form
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: 'date_joined' cannot be specified for CustomUser model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class CustomUserAdmin.
ERROR 2025-09-11 14:05:46,277 log 22588 6246445056 Internal Server Error: /admin/authentication/customuser/4/change/
Traceback (most recent call last):
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/options.py", line 840, in get_form
    return modelform_factory(self.model, **defaults)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/forms/models.py", line 654, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/forms/models.py", line 312, in __new__
    fields = fields_for_model(
        opts.model,
    ...<11 lines>...
        form_declared_fields=new_class.declared_fields,
    )
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/forms/models.py", line 207, in fields_for_model
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: 'date_joined' cannot be specified for CustomUser model form as it is a non-editable field

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1987, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1840, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1878, in _changeform_view
    ModelForm = self.get_form(
        request, obj, change=not add, fields=flatten_fieldsets(fieldsets)
    )
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/auth/admin.py", line 98, in get_form
    return super().get_form(request, obj, **defaults)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/options.py", line 842, in get_form
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: 'date_joined' cannot be specified for CustomUser model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class CustomUserAdmin.
INFO 2025-09-11 14:06:16,071 autoreload 22588 8786976960 /Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/authentication/urls.py changed, reloading.
INFO 2025-09-11 14:06:16,499 autoreload 23605 8786976960 Watching for file changes with StatReloader
INFO 2025-09-11 14:06:33,591 autoreload 23605 8786976960 /Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/authentication/admin.py changed, reloading.
INFO 2025-09-11 14:06:34,013 autoreload 23787 8786976960 Watching for file changes with StatReloader
INFO 2025-09-11 14:06:39,469 autoreload 23787 8786976960 /Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/authentication/admin.py changed, reloading.
INFO 2025-09-11 14:06:39,889 autoreload 23923 8786976960 Watching for file changes with StatReloader
INFO 2025-09-11 14:07:17,479 autoreload 25000 8786976960 Watching for file changes with StatReloader
INFO 2025-09-11 14:08:44,785 autoreload 26777 8786976960 Watching for file changes with StatReloader
INFO 2025-09-13 05:54:49,672 autoreload 51114 8654545088 Watching for file changes with StatReloader
WARNING 2025-09-13 05:54:53,131 log 51114 6196244480 Not Found: /favicon.ico
INFO 2025-09-16 04:14:44,460 autoreload 51832 8301977792 Watching for file changes with StatReloader
WARNING 2025-09-16 04:14:47,312 log 51832 6197981184 Not Found: /favicon.ico
INFO 2025-09-16 08:10:28,579 autoreload 55769 8301977792 Watching for file changes with StatReloader
INFO 2025-09-16 16:23:56,015 autoreload 14625 8517886144 Watching for file changes with StatReloader
WARNING 2025-09-16 16:23:58,581 log 14625 6222458880 Not Found: /favicon.ico
INFO 2025-09-17 02:06:08,241 autoreload 29634 8430444736 Watching for file changes with StatReloader
WARNING 2025-09-17 02:06:10,925 log 29634 6136737792 Not Found: /favicon.ico
INFO 2025-09-20 13:44:41,177 autoreload 56889 8579539136 Watching for file changes with StatReloader
INFO 2025-09-20 13:51:05,241 autoreload 63319 8579539136 Watching for file changes with StatReloader
WARNING 2025-09-20 13:51:08,459 log 63319 6189658112 Not Found: /favicon.ico
ERROR 2025-09-20 13:51:28,625 log 63319 6189658112 Internal Server Error: /admin/inventory/inventorytransaction/
Traceback (most recent call last):
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: inventory_location.location_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2024, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/options.py", line 867, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/views/main.py", line 145, in __init__
    self.queryset = self.get_queryset(request)
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/views/main.py", line 545, in get_queryset
    ) = self.get_filters(request)
        ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/views/main.py", line 216, in get_filters
    spec = field_list_filter_class(
        field,
    ...<4 lines>...
        field_path=field_path,
    )
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/filters.py", line 217, in create
    return list_filter_class(
        field, request, params, model, model_admin, field_path=field_path
    )
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/filters.py", line 232, in __init__
    self.lookup_choices = self.field_choices(field, request, model_admin)
                          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/contrib/admin/filters.py", line 273, in field_choices
    return field.get_choices(include_blank=False, ordering=ordering)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/db/models/fields/__init__.py", line 1083, in get_choices
    (choice_func(x), str(x)) for x in qs
                                      ^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/db/models/query.py", line 384, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: inventory_location.location_name
INFO 2025-09-20 13:58:06,577 autoreload 70770 8579539136 Watching for file changes with StatReloader
INFO 2025-09-20 14:10:27,444 test_logging 86869 8579539136 Test log message - logging is working!
INFO 2025-09-20 14:13:24,870 autoreload 89822 8579539136 Watching for file changes with StatReloader
WARNING 2025-09-20 14:15:25,166 log 22 281473438015520 Not Found: /api/
WARNING 2025-09-20 14:15:35,255 log 21 281473438015520 Unauthorized: /api/auth/
WARNING 2025-09-20 14:16:23,772 log 21 281473438015520 Not Found: /static/admin/css/login.css
WARNING 2025-09-20 14:16:25,306 log 20 281473438015520 Not Found: /static/admin/css/login.css
WARNING 2025-09-20 14:16:36,247 log 20 281473438015520 Not Found: /static/admin/css/base.css
WARNING 2025-09-20 14:16:36,247 log 21 281473438015520 Not Found: /static/admin/css/dark_mode.css
WARNING 2025-09-20 14:16:36,252 log 21 281473438015520 Not Found: /static/admin/css/login.css
WARNING 2025-09-20 14:16:36,251 log 20 281473438015520 Not Found: /static/admin/js/theme.js
WARNING 2025-09-20 14:16:36,254 log 21 281473438015520 Not Found: /static/admin/css/responsive.css
WARNING 2025-09-20 14:16:36,255 log 22 281473438015520 Not Found: /static/admin/css/nav_sidebar.css
WARNING 2025-09-20 14:16:36,319 log 22 281473438015520 Not Found: /static/admin/js/nav_sidebar.js
WARNING 2025-09-20 14:16:36,320 log 21 281473438015520 Not Found: /static/admin/css/nav_sidebar.css
WARNING 2025-09-20 14:16:36,320 log 20 281473438015520 Not Found: /static/admin/css/responsive.css
WARNING 2025-09-20 14:16:36,322 log 22 281473438015520 Not Found: /static/admin/css/login.css
WARNING 2025-09-20 14:16:36,945 log 20 281473438015520 Not Found: /favicon.ico
WARNING 2025-09-20 14:18:20,821 log 22 281473438015520 Not Found: /static/admin/css/base.css
WARNING 2025-09-20 14:19:34,637 log 20 281473663086624 Not Found: /static/admin/css/base.css
WARNING 2025-09-20 14:21:05,409 log 21 281473662734368 Not Found: /static/admin/css/base.css
ERROR 2025-09-20 14:21:21,310 log 30 281473341919264 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-09-20 14:24:05,872 log 20 281472849281056 Not Found: /static/admin/css/base.css
INFO 2025-09-23 09:03:43,492 autoreload 86569 8512020672 Watching for file changes with StatReloader
INFO 2025-09-23 09:04:52,618 autoreload 88040 8512020672 Watching for file changes with StatReloader
WARNING 2025-09-23 09:04:55,796 log 88040 6251753472 Not Found: /favicon.ico
WARNING 2025-09-23 17:52:41,115 log 22 281473121832992 Not Found: /static/admin/css/dashboard.css
WARNING 2025-09-23 17:52:41,134 log 22 281473121832992 Not Found: /static/admin/css/nav_sidebar.css
WARNING 2025-09-23 17:52:41,149 log 22 281473121832992 Not Found: /static/admin/css/responsive.css
WARNING 2025-09-23 17:52:41,163 log 22 281473121832992 Not Found: /static/admin/js/theme.js
WARNING 2025-09-23 17:52:41,216 log 21 281473121832992 Not Found: /static/admin/css/base.css
WARNING 2025-09-23 17:52:41,216 log 20 281473121832992 Not Found: /static/admin/css/dark_mode.css
WARNING 2025-09-23 17:52:41,234 log 22 281473121832992 Not Found: /static/admin/css/responsive.css
WARNING 2025-09-23 17:52:41,235 log 21 281473121832992 Not Found: /static/admin/css/nav_sidebar.css
WARNING 2025-09-23 17:52:41,235 log 20 281473121832992 Not Found: /static/admin/css/dashboard.css
WARNING 2025-09-23 17:52:41,247 log 22 281473121832992 Not Found: /static/admin/js/nav_sidebar.js
WARNING 2025-09-23 17:52:41,461 log 22 281473121832992 Not Found: /favicon.ico
WARNING 2025-09-23 18:04:51,111 log 24 281473853935648 Unauthorized: /api/manufacturing/api/purchase-orders/dashboard_stats/
WARNING 2025-09-23 18:04:51,111 log 23 281473853935648 Unauthorized: /api/manufacturing/api/manufacturing-orders/dashboard_stats/
INFO 2025-09-24 02:55:46,053 autoreload 5845 8647925952 Watching for file changes with StatReloader
ERROR 2025-09-24 02:56:06,539 log 5845 6171471872 Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
ERROR 2025-09-24 02:56:06,931 log 5845 6188298240 Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
INFO 2025-09-24 02:56:22,784 autoreload 6844 8647925952 Watching for file changes with StatReloader
INFO 2025-09-24 02:57:08,849 autoreload 7277 8647925952 Watching for file changes with StatReloader
WARNING 2025-09-24 02:57:12,734 log 7277 6201536512 Not Found: /favicon.ico
INFO 2025-09-24 04:35:08,657 autoreload 56704 8647925952 Watching for file changes with StatReloader
INFO 2025-09-24 04:35:33,281 autoreload 57324 8647925952 Watching for file changes with StatReloader
WARNING 2025-09-24 04:35:39,906 log 57324 6173241344 Not Found: /favicon.ico
INFO 2025-09-24 04:36:19,322 autoreload 58187 8647925952 Watching for file changes with StatReloader
INFO 2025-09-24 04:39:27,461 autoreload 64130 8647925952 Watching for file changes with StatReloader
INFO 2025-09-25 05:25:07,210 autoreload 87665 8643059904 Watching for file changes with StatReloader
WARNING 2025-09-25 05:25:09,555 log 87665 6287585280 Not Found: /favicon.ico
INFO 2025-09-27 03:58:21,444 autoreload 30329 8709038272 Watching for file changes with StatReloader
WARNING 2025-09-27 03:58:23,818 log 30329 6206763008 Not Found: /favicon.ico
INFO 2025-09-27 04:01:26,984 autoreload 33729 8709038272 Watching for file changes with StatReloader
INFO 2025-09-27 14:49:05,100 autoreload 74935 8709038272 Watching for file changes with StatReloader
WARNING 2025-09-27 14:50:51,303 log 74935 6172209152 Unauthorized: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 14:50:51,303 log 74935 6189035520 Unauthorized: /api/manufacturing/api/manufacturing-orders/dashboard_stats/
WARNING 2025-09-27 14:50:51,303 log 74935 6205861888 Unauthorized: /api/manufacturing/api/purchase-orders/dashboard_stats/
WARNING 2025-09-27 14:50:51,307 log 74935 6222688256 Unauthorized: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 14:51:18,660 log 74935 6205861888 Unauthorized: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 14:51:18,661 log 74935 6222688256 Unauthorized: /api/manufacturing/api/manufacturing-orders/dashboard_stats/
WARNING 2025-09-27 14:51:18,662 log 74935 6189035520 Unauthorized: /api/manufacturing/api/purchase-orders/dashboard_stats/
WARNING 2025-09-27 14:51:18,668 log 74935 6172209152 Unauthorized: /api/manufacturing/api/manufacturing-orders/
INFO 2025-09-27 14:52:13,541 autoreload 80464 8709038272 Watching for file changes with StatReloader
WARNING 2025-09-27 14:52:19,281 log 80464 6196736000 Unauthorized: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 14:52:19,281 log 80464 6213562368 Unauthorized: /api/manufacturing/api/manufacturing-orders/dashboard_stats/
WARNING 2025-09-27 14:52:19,282 log 80464 6230388736 Unauthorized: /api/manufacturing/api/purchase-orders/dashboard_stats/
WARNING 2025-09-27 14:52:19,286 log 80464 6213562368 Unauthorized: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 14:52:49,262 log 80464 6213562368 Unauthorized: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 14:53:19,258 log 80464 6213562368 Unauthorized: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 14:53:49,254 log 80464 6213562368 Unauthorized: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 14:54:19,260 log 80464 6213562368 Unauthorized: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 14:54:49,263 log 80464 6213562368 Unauthorized: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 14:55:19,263 log 80464 6213562368 Unauthorized: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 14:55:53,271 log 80464 6213562368 Unauthorized: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 14:56:53,271 log 80464 6213562368 Unauthorized: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 14:57:39,886 log 80464 6213562368 Unauthorized: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 14:58:20,103 log 80464 6213562368 Not Found: /api/auth/manager/login
WARNING 2025-09-27 14:58:27,034 log 80464 6213562368 Not Found: /api/auth/manager/login
WARNING 2025-09-27 15:00:28,330 log 80464 6196736000 Bad Request: /api/auth/login/
WARNING 2025-09-27 15:01:38,461 log 80464 6213562368 Bad Request: /api/auth/login/
WARNING 2025-09-27 15:05:06,694 log 80464 6196736000 Bad Request: /api/auth/login/
WARNING 2025-09-27 15:05:38,644 log 80464 6196736000 Not Found: /api/manufacturing/manufacturing-orders/dashboard_stats/
WARNING 2025-09-27 15:05:38,663 log 80464 6230388736 Not Found: /api/manufacturing/purchase-orders/dashboard_stats/
WARNING 2025-09-27 15:05:38,665 log 80464 6213562368 Not Found: /api/manufacturing/manufacturing-orders/
WARNING 2025-09-27 15:05:38,695 log 80464 6213562368 Not Found: /api/manufacturing/manufacturing-orders/
WARNING 2025-09-27 15:06:09,268 log 80464 6213562368 Not Found: /api/manufacturing/manufacturing-orders/
WARNING 2025-09-27 15:06:38,631 log 80464 6213562368 Not Found: /api/manufacturing/manufacturing-orders/
WARNING 2025-09-27 15:07:09,268 log 80464 6213562368 Not Found: /api/manufacturing/manufacturing-orders/
WARNING 2025-09-27 15:07:39,272 log 80464 6213562368 Not Found: /api/manufacturing/manufacturing-orders/
WARNING 2025-09-27 15:07:42,690 log 80464 6264041472 Unauthorized: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 15:07:54,079 log 80464 6264041472 Unauthorized: /api/manufacturing/api/manufacturing-orders/dashboard_stats/
WARNING 2025-09-27 15:08:07,531 log 80464 6230388736 Forbidden: /api/manufacturing/api/manufacturing-orders/dashboard_stats/
WARNING 2025-09-27 15:08:07,532 log 80464 6196736000 Forbidden: /api/manufacturing/api/purchase-orders/dashboard_stats/
WARNING 2025-09-27 15:08:07,533 log 80464 6213562368 Forbidden: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 15:08:07,546 log 80464 6247215104 Forbidden: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 15:08:38,274 log 80464 6247215104 Forbidden: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 15:09:08,274 log 80464 6247215104 Forbidden: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 15:09:38,273 log 80464 6247215104 Forbidden: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 15:10:08,273 log 80464 6247215104 Forbidden: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 15:10:38,268 log 80464 6247215104 Forbidden: /api/manufacturing/api/manufacturing-orders/
WARNING 2025-09-27 15:10:47,306 log 80464 6264041472 Forbidden: /api/manufacturing/api/manufacturing-orders/dashboard_stats/
WARNING 2025-09-27 15:11:08,276 log 80464 6247215104 Forbidden: /api/manufacturing/api/manufacturing-orders/
INFO 2025-09-27 15:11:25,528 autoreload 80464 8709038272 /Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/manufacturing/permissions.py changed, reloading.
INFO 2025-09-27 15:11:26,205 autoreload 13763 8709038272 Watching for file changes with StatReloader
INFO 2025-09-27 15:12:38,696 autoreload 13763 8709038272 /Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/manufacturing/permissions.py changed, reloading.
INFO 2025-09-27 15:12:39,331 autoreload 15810 8709038272 Watching for file changes with StatReloader
INFO 2025-09-27 15:12:40,687 autoreload 15810 8709038272 /Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/manufacturing/permissions.py changed, reloading.
INFO 2025-09-27 15:12:41,168 autoreload 15851 8709038272 Watching for file changes with StatReloader
INFO 2025-09-27 15:12:42,602 autoreload 15851 8709038272 /Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/manufacturing/permissions.py changed, reloading.
INFO 2025-09-27 15:12:43,110 autoreload 15896 8709038272 Watching for file changes with StatReloader
INFO 2025-09-27 15:12:49,759 autoreload 15896 8709038272 /Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/manufacturing/permissions.py changed, reloading.
INFO 2025-09-27 15:12:50,253 autoreload 16137 8709038272 Watching for file changes with StatReloader
ERROR 2025-09-27 15:16:56,703 log 16137 6153973760 Internal Server Error: /api/manufacturing/api/purchase-orders/raw_materials/
Traceback (most recent call last):
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/manufacturing/views.py", line 323, in raw_materials
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 523, in to_representation
    for field in fields:
                 ^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `product_code` is not valid for model `RawMaterial` in `manufacturing.serializers.RawMaterialDropdownSerializer`.
ERROR 2025-09-27 15:16:56,740 log 16137 6137147392 Internal Server Error: /api/manufacturing/api/purchase-orders/raw_materials/
Traceback (most recent call last):
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/manufacturing/views.py", line 323, in raw_materials
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 523, in to_representation
    for field in fields:
                 ^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `product_code` is not valid for model `RawMaterial` in `manufacturing.serializers.RawMaterialDropdownSerializer`.
ERROR 2025-09-27 15:17:37,109 log 16137 6204452864 Internal Server Error: /api/manufacturing/api/purchase-orders/raw_materials/
Traceback (most recent call last):
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/manufacturing/views.py", line 323, in raw_materials
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 523, in to_representation
    for field in fields:
                 ^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `product_code` is not valid for model `RawMaterial` in `manufacturing.serializers.RawMaterialDropdownSerializer`.
INFO 2025-09-27 15:18:14,680 autoreload 16137 8709038272 /Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/manufacturing/serializers.py changed, reloading.
INFO 2025-09-27 15:18:15,414 autoreload 25042 8709038272 Watching for file changes with StatReloader
INFO 2025-09-27 15:18:39,052 autoreload 25042 8709038272 /Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/manufacturing/serializers.py changed, reloading.
INFO 2025-09-27 15:18:39,610 autoreload 25696 8709038272 Watching for file changes with StatReloader
INFO 2025-09-27 15:19:09,620 autoreload 25696 8709038272 /Users/jayakumarn/Documents/personal/microsprings/Microsprings-inventory-managemenet-system/manufacturing/serializers.py changed, reloading.
INFO 2025-09-27 15:19:10,271 autoreload 26576 8709038272 Watching for file changes with StatReloader
